name: custom_customer_demo_snowflake
version: "1.0.0"
config-version: 2

profile: custom_customer_demo_snowflake

dbt-cloud:
  project-id: 558500
  defer-env-id: 465571

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]

clean-targets:
  - "target"
  - "dbt_packages"
